name: 'github-comment-slack-channeler'
description: 'A job to share github comment as unfurl'
inputs:
  github_token:
    description: 'github token'
    required: true
  slack_bot_token:
    description: 'slack bot token'
    required: true
  github_comment_url:
    description: 'github comment url'
    required: true
  channeler_target_config:
    description: 'if these key are included, then do this job.'
    required: true
  unfurl_links_context:
    description: 'if this key is true, then unfurl github comment url which is in body text'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'index.js'
