name: 'github-comment-slack-channeler'
description: 'A job to share github comment as unfurl'
inputs:
  github_token:
    description: 'github token'
    required: true
  slack_bot_token:
    description: 'slack bot token'
    required: true
  slack_channel_id:
    description: 'slack channel id'
    required: true
  github_comment_url:
    description: 'github comment url'
    required: true

# runs:
#   using: 'docker'
#   image: 'Dockerfile'
runs:
  using: 'node12'
  main: 'index.js'
