name: 'github-comment-slack-channeler'
description: 'A job to share github comment as unfurl'
inputs:
  slack_bot_token:
    description: 'slack bot token'
    required: true
  slack_channel_id:
    description: 'slack channel id'
    required: true
  comment_url_text:
    description: 'github url of the comment'
    required: true
  slack_channeler_github_token:
    description: 'github token for fetch comment data'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.slack_bot_token }}
    - ${{ inputs.slack_channel_id }}
    - ${{ inputs.comment_url_text }}
    - ${{ inputs.slack_channeler_github_token }}
