on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello on mine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        id: hello
        # uses: stNamco/github-comment-slack-channeler@v1
        uses: ./
        with:
          slack_bot_token: 'test slack_bot_token'
          slack_channel_id: 'test slack_channel_id'
          comment_url_text: 'test comment_url_text'
          slack_channeler_github_token: 'test slack_channeler_github_token'


      # `hello` ステップからの出力を使用する
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
