name: github comment slack channeler

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to share github comment as unfurl
    steps:
      - name: unfurl action step
        id: unfurl_comment
        if: contains(github.event.comment.body, '/share')
        uses: stNamco/github-comment-slack-channeler@v0.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack_channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          github_comment_url: ${{ github.event.comment.html_url }}
