on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to share github comment as unfurl
    steps:
      - name: unfurl action step
        id: hello
        uses: stNamco/github-comment-slack-channeler@6f9fa0f51c8b9abfb055b434ade21f6a88903bdc
        with:
          slack_bot_token: 'test-slack_bot_token'
          slack_channel_id: 'test-slack_channel_id'
          comment_url_text: 'test-comment_url_text'
          slack_channeler_github_token: 'test-slack_channeler_github_token'
